pipeline:
  name: Build casper-node
  identifier: Build_casper_network_casper_node_1701192539136
  projectIdentifier: caspernode
  orgIdentifier: default
  stages:
    - stage:
        name: Build Node
        identifier: Build_Node
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.casperkube
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Node
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: casperlabs/node-build-u1804
                    shell: Bash
                    command: |-
                      cargo install elfx86exts --version 0.5.0
                      make setup
                      make test CARGO_FLAGS=--release
                      make test-contracts CARGO_FLAGS=--release
                    resources:
                      limits:
                        memory: 14Gi
                        cpu: "12"
  properties:
    ci:
      codebase:
        connectorRef: org.casperdrone_github_connector
        repoName: casper-node
        build: <+input>
